/**:
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: false
    costmap_topic: /map
    costmap_updates_topic: /map_updates
    visualize: true
    planner_frequency: 0.5
    progress_timeout: 20.0
    lock_goal_until_done: true
    goal_timeout: 45.0
    goal_retry_limit: 1
    goal_retry_delay: 2.0
    potential_scale: 3.0
    orientation_scale: 0.0
    gain_scale: 1.0
    transform_tolerance: 1.0
    min_frontier_size: 1.5
