pois:
- id: wp_005
  display_name: wp_005
  poi_type: waypoint
  floor_id: floor_4
  area_id: floor_4_unassigned
  x: -3.525
  y: 2.555
  yaw: 1.5316159229932882
  final_approach_profile: doorway
  enabled: true
  map_version: floor_4-v1
- id: wp_006
  display_name: 电梯测试等待点
  poi_type: waypoint
  floor_id: floor_4
  area_id: floor_4_unassigned
  x: -3.155
  y: 1.815
  yaw: 1.628
  final_approach_profile: none
  enabled: true
  map_version: floor_4-v1
- id: wp_007
  display_name: home(充电点)
  poi_type: waypoint
  floor_id: floor_4
  area_id: floor_4_unassigned
  x: -2.009607577807847
  y: 0.20488410805171853
  yaw: 0.0
  final_approach_profile: none
  enabled: true
  map_version: floor_4-v1
- id: wp_008
  display_name: 厨房
  poi_type: waypoint
  floor_id: floor_4
  area_id: floor_4_unassigned
  x: 0.131
  y: -0.192
  yaw: 0.0
  final_approach_profile: none
  enabled: true
  map_version: floor_4-v1
- id: wp_009
  display_name: 卧室
  poi_type: waypoint
  floor_id: floor_4
  area_id: floor_4_unassigned
  x: -1.694
  y: -0.864
  yaw: 0.0
  final_approach_profile: none
  enabled: true
  map_version: floor_4-v1
- id: wp_010
  display_name: 浴室
  poi_type: waypoint
  floor_id: floor_4
  area_id: floor_4_unassigned
  x: -1.1098105548037882
  y: -0.14342441698211061
  yaw: 0.0
  final_approach_profile: none
  enabled: true
  map_version: floor_4-v1
