joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 30.0
    sticky_buttons: false
gamepad_teleop:
  ros__parameters:
    joy_topic: /joy
    cmd_vel_topic: /nx/gamepad_unverified_cmd_vel
    enabled_topic: /gamepad/enabled
    axis_forward: 1
    axis_lateral: 0
    axis_yaw: 3
    speed_down_button: 2
    speed_up_button: 3
    enable_button: 4
    turbo_button: 5
    require_enable_button: true
    scale_forward: 0.40
    scale_lateral: 0.40
    scale_yaw: 0.80
    turbo_scale_forward: 0.40
    turbo_scale_lateral: 0.40
    turbo_scale_yaw: 0.80
    deadzone: 0.10
    axis_exponent: 1.50
    publish_rate: 30.0
    joy_timeout: 0.20
    stop_publish_duration: 0.30
