pois:
- id: auto_refrigerator_001
  display_name: 冰箱
  poi_type: waypoint
  floor_id: floor_3
  area_id: floor_3_unassigned
  x: -0.36613361101380043
  y: 1.9561495491176573
  yaw: 0.8726646259971647
  final_approach_profile: none
  enabled: true
  map_version: floor_3-v1
  generated_by: ddsm_car_control/semantic_mapping_recorder
  source_object_id: auto_refrigerator_001
  source_object_class: refrigerator
  source_object_x: 0.3087933791570659
  source_object_y: 2.760496214392584
  source_confidence: 0.5376513997713724
  clearance: 0.5099019589574096
- id: auto_chair_001
  display_name: 椅子
  poi_type: waypoint
  floor_id: floor_3
  area_id: floor_3_unassigned
  x: -1.9558893206088286
  y: 0.31809960858860475
  yaw: 1.2217304763960302
  final_approach_profile: none
  enabled: true
  map_version: floor_3-v1
  generated_by: ddsm_car_control/semantic_mapping_recorder
  source_object_id: auto_chair_001
  source_object_class: chair
  source_object_x: -1.6651721987820096
  source_object_y: 1.1168383362566268
  source_confidence: 0.8333224654197693
  clearance: 0.62
