pois:
- id: wp_001
  display_name: 门口
  poi_type: waypoint
  floor_id: floor_2
  area_id: floor_2_unassigned
  x: 0.5793659138309009
  y: 1.070841138643464
  yaw: 0.02465415732886604
  final_approach_profile: doorway
  enabled: true
  map_version: floor_2-v1
- id: wp_002
  display_name: 客厅
  poi_type: waypoint
  floor_id: floor_2
  area_id: floor_2_unassigned
  x: -2.103035609768815
  y: -0.6258260783786835
  yaw: 1.554360625530205
  final_approach_profile: doorway
  enabled: true
  map_version: floor_2-v1
- id: wp_003
  display_name: 厨房
  poi_type: waypoint
  floor_id: floor_2
  area_id: floor_2_unassigned
  x: -1.230294817150984
  y: -2.685498576690152
  yaw: 1.929623425440331
  final_approach_profile: doorway
  enabled: true
  map_version: floor_2-v1
- id: wp_004
  display_name: 厕所
  poi_type: waypoint
  floor_id: floor_2
  area_id: floor_2_unassigned
  x: -3.989875929645792
  y: 0.1884803502795109
  yaw: -0.1288504676353266
  final_approach_profile: doorway
  enabled: true
  map_version: floor_2-v1
- id: auto_door_001
  display_name: 门
  poi_type: waypoint
  floor_id: floor_2
  area_id: floor_2_unassigned
  x: -4.2888353435847195
  y: 1.2972437390241616
  yaw: 0.3490658503988657
  final_approach_profile: none
  enabled: true
  map_version: floor_2-v1
  generated_by: ddsm_car_control/semantic_mapping_recorder
  source_object_id: auto_door_001
  source_object_class: door
  source_object_x: -3.490096615916697
  source_object_y: 1.5879608608509799
  source_confidence: 0.7609661320845286
  clearance: 0.6000000089406967
- id: auto_door_003
  display_name: 门3
  poi_type: waypoint
  floor_id: floor_2
  area_id: floor_2_unassigned
  x: -0.9097502997718736
  y: -0.13200209437311317
  yaw: -1.9198621771937627
  final_approach_profile: none
  enabled: true
  map_version: floor_2-v1
  generated_by: ddsm_car_control/semantic_mapping_recorder
  source_object_id: auto_door_003
  source_object_class: door
  source_object_x: -1.2004674215986921
  source_object_y: -0.9307408220411352
  source_confidence: 0.7581163644790649
  clearance: 0.62
- id: auto_door_004
  display_name: 门4
  poi_type: waypoint
  floor_id: floor_2
  area_id: floor_2_unassigned
  x: 2.1596970345766144
  y: 1.0520340149415572
  yaw: 3.141592653589793
  final_approach_profile: none
  enabled: true
  map_version: floor_2-v1
  generated_by: ddsm_car_control/semantic_mapping_recorder
  source_object_id: auto_door_004
  source_object_class: door
  source_object_x: 1.3096970345766146
  source_object_y: 1.0520340149415572
  source_confidence: 0.7581163644790649
  clearance: 0.62
- id: auto_door_005
  display_name: 门5
  poi_type: waypoint
  floor_id: floor_2
  area_id: floor_2_unassigned
  x: -2.525796954884821
  y: 0.02031390253111709
  yaw: 0.6981317007977318
  final_approach_profile: none
  enabled: true
  map_version: floor_2-v1
  generated_by: ddsm_car_control/semantic_mapping_recorder
  source_object_id: auto_door_005
  source_object_class: door
  source_object_x: -1.8746591782336899
  source_object_y: 0.5666833707646755
  source_confidence: 0.7581163644790649
  clearance: 0.62
- id: auto_door_006
  display_name: 门6
  poi_type: waypoint
  floor_id: floor_2
  area_id: floor_2_unassigned
  x: 2.2035705007175372
  y: -0.46489558880072757
  yaw: -2.9670597283903604
  final_approach_profile: none
  enabled: true
  map_version: floor_2-v1
  generated_by: ddsm_car_control/semantic_mapping_recorder
  source_object_id: auto_door_006
  source_object_class: door
  source_object_x: 1.3664839106571605
  source_object_y: -0.6124965398176183
  source_confidence: 0.7581163644790649
  clearance: 0.6082762620938444
