from setuptools import setup
import os
from glob import glob

package_name = 'ddsm_car_control'

setup(
    name=package_name,
    version='1.0.0',
    packages=[package_name],
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        (os.path.join('share', package_name, 'launch'),
            glob('launch/*.launch.py')),
        (os.path.join('share', package_name, 'config'),
            glob('config/*.yaml')),
        (os.path.join('share', package_name, 'urdf'), glob('urdf/*.urdf')),
        (os.path.join('share', package_name, 'meshes'), glob('meshes/*')),
        (os.path.join('share', package_name, 'behavior_trees'),
            glob('behavior_trees/*.xml')),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='user',
    maintainer_email='user@example.com',
    description='ROS2 node for 4-wheel differential drive DDSM car',
    license='MIT',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'cmd_vel_to_ddsm = ddsm_car_control.cmd_vel_to_ddsm:main',
            'udp_cmd_vel_bridge = ddsm_car_control.udp_cmd_vel_bridge:main',
            'zdt_mecanum_rs485_bridge = ddsm_car_control.zdt_mecanum_rs485_bridge:main',
            'encoder_logger = ddsm_car_control.encoder_logger:main',
            'nav_lifecycle_autostarter = ddsm_car_control.nav_lifecycle_autostarter:main',
            'slam_lifecycle_autostarter = ddsm_car_control.slam_lifecycle_autostarter:main',
            'map_republisher = ddsm_car_control.map_republisher:main',
            'scan_throttler = ddsm_car_control.scan_throttler:main',
            'laser_scan_deskewer = ddsm_car_control.laser_scan_deskewer:main',
            'wit_imu_node = ddsm_car_control.wit_imu_node:main',
            'ddsm_home_manager = ddsm_car_control.ddsm_home_manager:main',
            'ddsm_final_approach_navigator = ddsm_car_control.final_approach_navigator:main',
            'ddsm_auto_localizer = ddsm_car_control.ddsm_auto_localizer:main',
            'ddsm_patrol_manager = ddsm_car_control.ddsm_patrol_manager:main',
            'ddsm_waterplus_bridge = ddsm_car_control.waterplus_waypoint_bridge:main',
            'ddsm_mission_control = ddsm_car_control.ddsm_mission_control:main',
            'ddsm_multifloor_manager = ddsm_car_control.ddsm_multifloor_manager:main',
            'ddsm_elevator_adapter = ddsm_car_control.ddsm_elevator_adapter:main',
            'elevator_entry_controller = ddsm_car_control.elevator_entry_controller:main',
            'ddsm_lateral_escape_guard = ddsm_car_control.lateral_escape_guard:main',
            'gamepad_teleop = ddsm_car_control.gamepad_teleop:main',
            'semantic_mapping_recorder = ddsm_car_control.semantic_mapping_recorder:main',
            'depth_obstacle_monitor = ddsm_car_control.depth_obstacle_monitor:main',
            'dual_laser_fusion = ddsm_car_control.dual_laser_fusion:main',
            'low_lidar_udp_proxy = ddsm_car_control.low_lidar_udp_proxy:main',
            'colored_point_cloud_relay = ddsm_car_control.colored_point_cloud_relay:main',
        ],
    },
)
