pois:
- id: home
  display_name: 充电点
  poi_type: home
  floor_id: floor_1
  area_id: floor_1_unassigned
  x: -1.2133374365475493
  y: 0.48838636683492
  yaw: 1.2854961520010955
  final_approach_profile: none
  enabled: true
  map_version: 2026.07.13-v1
- id: wp_001
  display_name: 办公桌
  poi_type: waypoint
  floor_id: floor_1
  area_id: floor_1_unassigned
  x: 0.609976888629133
  y: -0.5571042068999
  yaw: -0.2197189891945507
  final_approach_profile: doorway
  enabled: true
  map_version: 2026.07.13-v1
- id: wp_002
  display_name: 沙发
  poi_type: waypoint
  floor_id: floor_1
  area_id: floor_1_unassigned
  x: -1.3320874595877448
  y: -1.2482963337901065
  yaw: -2.633466710709893
  final_approach_profile: doorway
  enabled: true
  map_version: 2026.07.13-v1
- id: wp_003
  display_name: 门口
  poi_type: waypoint
  floor_id: floor_1
  area_id: floor_1_unassigned
  x: -0.7408813429318337
  y: 1.8145882145205219
  yaw: 1.3927942077167546
  final_approach_profile: doorway
  enabled: true
  map_version: 2026.07.13-v1
- id: wp_004
  display_name: 茶桌
  poi_type: waypoint
  floor_id: floor_1
  area_id: floor_1_unassigned
  x: -1.5139162682266651
  y: 0.03394112096373747
  yaw: -0.3354248123440516
  final_approach_profile: doorway
  enabled: true
  map_version: 2026.07.13-v1
- id: wp_005
  display_name: wp_005
  poi_type: waypoint
  floor_id: floor_1
  area_id: floor_1_unassigned
  x: -1.4295274660790422
  y: 4.348342148268159
  yaw: 1.3110437789485223
  final_approach_profile: doorway
  enabled: true
  map_version: 2026.07.13-v1
- id: auto_chair_001
  display_name: 椅子
  poi_type: waypoint
  floor_id: floor_1
  area_id: floor_1_unassigned
  x: -1.260157720244825
  y: 0.6032768149444405
  yaw: 3.141592653589793
  final_approach_profile: none
  enabled: true
  map_version: 2026.07.13-v1
  generated_by: ddsm_car_control/semantic_mapping_recorder
  source_object_id: auto_chair_001
  source_object_class: chair
  source_object_x: -2.110157720244825
  source_object_y: 0.6032768149444405
  source_confidence: 0.7927083333333333
  clearance: 0.62
- id: auto_refrigerator_001
  display_name: 冰箱
  poi_type: waypoint
  floor_id: floor_1
  area_id: floor_1_unassigned
  x: -2.319865398295585
  y: 2.2566882368611987
  yaw: 2.7925268031909267
  final_approach_profile: none
  enabled: true
  map_version: 2026.07.13-v1
  generated_by: ddsm_car_control/semantic_mapping_recorder
  source_object_id: auto_refrigerator_001
  source_object_class: refrigerator
  source_object_x: -3.212573388042198
  source_object_y: 2.5816073730205846
  source_confidence: 0.7240234375
  clearance: 0.6103277898812778
- id: auto_door_001
  display_name: 门
  poi_type: waypoint
  floor_id: floor_1
  area_id: floor_1_unassigned
  x: -1.6163710620419747
  y: 2.61217615379205
  yaw: 1.5707963267948963
  final_approach_profile: none
  enabled: true
  map_version: 2026.07.13-v1
  generated_by: ddsm_car_control/semantic_mapping_recorder
  source_object_id: auto_door_001
  source_object_class: door
  source_object_x: -1.6163710620419744
  source_object_y: 3.46217615379205
  source_confidence: 0.7567458550135294
  clearance: 0.62
- id: wp_006
  display_name: 门外
  poi_type: waypoint
  floor_id: floor_1
  area_id: floor_1_unassigned
  x: -3.683928387904807
  y: 3.9672451133189774
  yaw: 0.0
  final_approach_profile: none
  enabled: true
  map_version: floor_1-dashboard
- id: wp_007
  display_name: 电梯测试等待点
  poi_type: waypoint
  floor_id: floor_1
  area_id: floor_1_unassigned
  x: -1.673527
  y: 3.430211
  yaw: 1.311044
  final_approach_profile: none
  enabled: true
  map_version: floor_1-dashboard
